title: GetAIzed
author: GetAIzed
description: A modern blog exploring the latest in Artificial Intelligence, machine learning, and the future of technology.
baseurl: ""
url: "https://getaized.github.io"

markdown: kramdown
theme: minima
permalink: pretty

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
